// <auto-generated />
using A_DOT_NET.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContosoPizza.Migrations
{
    [DbContext(typeof(AlbumContext))]
    partial class AlbumContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("A_DOT_NET.models.Album_cd", b =>
                {
                    b.Property<int>("Album_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Album_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Artist_name")
                        .IsRequired()
                        .HasColumnType("TEXT");
                    
                    b.Property<int>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    

                    b.HasKey("Album_id");

                    b.ToTable("albums");
                });
#pragma warning restore 612, 618
        }
    }
}
